### ISSUE TITLE
都获取不到数据了，服务器关了吗

### ISSUE THREAD

**Issue by dhhuanghui** [TongmingWu/Manga#1]

**Comment by TongmingWu** [comment]
服务器很久没用,被回收了- -

**Comment by ghost** [comment]
@TongmingWu 有服务器端代码吗，想运行一下看看效果。或者其他方式也行

**Comment by Zhjoker** [comment]
有没有漫画数据呢？

**Comment by zxkang** [comment]
没有数据了，求开放服务端源码

**Comment by TongmingWu** [comment]
这个项目已经不再维护了，服务端代码现在也是用不了的，因为目标网站早已改版，是抓取不到数据的，抱歉

**Comment by zxkang** [comment]
感谢答复

> 这个项目已经不再维护了，服务端代码现在也是用不了的，因为目标网站早已改版，是抓取不到数据的，抱歉
